config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }
  authenticate :user do
    resources :sediments
  end
  resources :laboratories
  resources :departments
  resources :centers
  root to: "home#index"

  authenticated :user, lambda { |u| u.admin? } do
    get 'list', to: 'users#index'
    post 'approve', to: 'users#approve'
  end

  devise_scope :user do

    get 'users/update_departments', to: 'users/registrations#update_departments'
    get 'users/update_laboratories', to: 'users/registrations#update_laboratories'
  end
end

app/models/laboratory.rb
class Laboratory < ApplicationRecord
  has_one :user
  has_many :sediments
  belongs_to :department
end

app/controllers/laboratories_controller.rb
class LaboratoriesController < ApplicationController
  before_action :set_laboratory, only: [:show, :edit, :update, :destroy]

  # GET /laboratories
  # GET /laboratories.json
  def index
    @laboratories = Laboratory.all
  end

  # GET /laboratories/1
  # GET /laboratories/1.json
  def show
  end

  # GET /laboratories/new
  def new
    @laboratory = Laboratory.new
  end

  # GET /laboratories/1/edit
  def edit
  end

  # POST /laboratories
  # POST /laboratories.json
  def create
    @laboratory = Laboratory.new(laboratory_params)

    respond_to do |format|
      if @laboratory.save
        format.html { redirect_to @laboratory, notice: 'Laboratory was successfully created.' }
        format.json { render :show, status: :created, location: @laboratory }
      else
        format.html { render :new }
        format.json { render json: @laboratory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /laboratories/1
  # PATCH/PUT /laboratories/1.json
  def update
    respond_to do |format|
      if @laboratory.update(laboratory_params)
        format.html { redirect_to @laboratory, notice: 'Laboratory was successfully updated.' }
        format.json { render :show, status: :ok, location: @laboratory }
      else
        format.html { render :edit }
        format.json { render json: @laboratory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laboratories/1
  # DELETE /laboratories/1.json
  def destroy
    @laboratory.destroy
    respond_to do |format|
      format.html { redirect_to laboratories_url, notice: 'Laboratory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_laboratory
      @laboratory = Laboratory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def laboratory_params
      params.require(:laboratory).permit(:name, :user_id, :department_id)
    end
end

app/helpers/laboratories_helper.rb
module LaboratoriesHelper
end

app/views/laboratories/_form.html.erb
<%= form_for(laboratory) do |f| %>
  <% if laboratory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(laboratory.errors.count, "error") %> prohibited this laboratory from being saved:</h2>

      <ul>
      <% laboratory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :department_id %>
    <%= f.text_field :department_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/laboratories/_laboratory.html.erb
<option value="<%= laboratory.id %>"><%= laboratory.name %></option>

app/views/laboratories/edit.html.erb
<h1>Editing Laboratory</h1>

<%= render 'form', laboratory: @laboratory %>

<%= link_to 'Show', @laboratory %> |
<%= link_to 'Back', laboratories_path %>

app/views/laboratories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Laboratories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @laboratories.each do |laboratory| %>
      <tr>
        <td><%= laboratory.name %></td>
        <td><%= laboratory.user %></td>
        <td><%= link_to 'Show', laboratory %></td>
        <td><%= link_to 'Edit', edit_laboratory_path(laboratory) %></td>
        <td><%= link_to 'Destroy', laboratory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Laboratory', new_laboratory_path %>

app/views/laboratories/new.html.erb
<h1>New Laboratory</h1>

<%= render 'form', laboratory: @laboratory %>

<%= link_to 'Back', laboratories_path %>

app/views/laboratories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @laboratory.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @laboratory.user %>
</p>

<%= link_to 'Edit', edit_laboratory_path(@laboratory) %> |
<%= link_to 'Back', laboratories_path %>