config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }
  authenticate :user do
    resources :sediments
  end
  resources :laboratories
  resources :departments
  resources :centers
  root to: "home#index"

  authenticated :user, lambda { |u| u.admin? } do
    get 'list', to: 'users#index'
    post 'approve', to: 'users#approve'
  end

  devise_scope :user do

    get 'users/update_departments', to: 'users/registrations#update_departments'
    get 'users/update_laboratories', to: 'users/registrations#update_laboratories'
  end
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :center
  has_many :laboratories
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name, :center_id, :chief, :email, :phone_ext)
    end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_department.html.erb
<option value="<%= department.id %>"><%= department.name %></option>

app/views/departments/_form.html.erb
<%= form_for(department) do |f| %>
  <% if department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :center_id %>
    <%= f.text_field :center_id %>
  </div>

  <div class="field">
    <%= f.label :chief %>
    <%= f.text_field :chief %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :phone_ext %>
    <%= f.text_field :phone_ext %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing Department</h1>

<%= render 'form', department: @department %>

<%= link_to 'Show', @department %> |
<%= link_to 'Back', departments_path %>

app/views/departments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Center</th>
      <th>Chief</th>
      <th>Email</th>
      <th>Phone ext</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.name %></td>
        <td><%= department.center %></td>
        <td><%= department.chief %></td>
        <td><%= department.email %></td>
        <td><%= department.phone_ext %></td>
        <td><%= link_to 'Show', department %></td>
        <td><%= link_to 'Edit', edit_department_path(department) %></td>
        <td><%= link_to 'Destroy', department, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Department', new_department_path %>

app/views/departments/new.html.erb
<h1>New Department</h1>

<%= render 'form', department: @department %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @department.name %>
</p>

<p>
  <strong>Center:</strong>
  <%= @department.center %>
</p>

<p>
  <strong>Chief:</strong>
  <%= @department.chief %>
</p>

<p>
  <strong>Email:</strong>
  <%= @department.email %>
</p>

<p>
  <strong>Phone ext:</strong>
  <%= @department.phone_ext %>
</p>

<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>