config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }
  authenticate :user do
    resources :sediments
  end
  resources :laboratories
  resources :departments
  resources :centers
  root to: "home#index"

  authenticated :user, lambda { |u| u.admin? } do
    get 'list', to: 'users#index'
    post 'approve', to: 'users#approve'
  end

  devise_scope :user do

    get 'users/update_departments', to: 'users/registrations#update_departments'
    get 'users/update_laboratories', to: 'users/registrations#update_laboratories'
  end
end

app/models/sediment.rb
class Sediment < ApplicationRecord
  belongs_to :user
  belongs_to :laboratory

  validates :weight, presence: true
  validates :composition, presence: true
  validates :res_type, presence: true
end

app/controllers/sediments_controller.rb
class SedimentsController < ApplicationController
  before_action :set_sediment, only: [:show, :edit, :update, :destroy]

  # GET /sediments
  # GET /sediments.json
  def index
    @sediments = Sediment.all
  end

  # GET /sediments/1
  # GET /sediments/1.json
  def show
  end

  # GET /sediments/new
  def new
    @sediment = Sediment.new
  end

  # GET /sediments/1/edit
  def edit
  end

  # POST /sediments
  # POST /sediments.json
  def create
    @sediment = Sediment.new(sediment_params)
    @sediment.data_registered = Time.now
    @sediment.laboratory = current_user.laboratory
    @sediment.user = current_user
    @sediment.local = current_user.laboratory
    respond_to do |format|
      if @sediment.save
        format.html { redirect_to @sediment, notice: 'Residuo foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @sediment }
      else
        format.html { render :new }
        format.json { render json: @sediment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sediments/1
  # PATCH/PUT /sediments/1.json
  def update
    respond_to do |format|
      if @sediment.update(sediment_params)
        format.html { redirect_to @sediment, notice: 'Sediment was successfully updated.' }
        format.json { render :show, status: :ok, location: @sediment }
      else
        format.html { render :edit }
        format.json { render json: @sediment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sediments/1
  # DELETE /sediments/1.json
  def destroy
    @sediment.destroy
    respond_to do |format|
      format.html { redirect_to sediments_url, notice: 'Sediment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sediment
      @sediment = Sediment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sediment_params
      params.require(:sediment).permit(:composition, :weight, :local, :data_created,:res_type ,:data_registered)
    end
end

app/helpers/sediments_helper.rb
module SedimentsHelper
end

app/views/sediments/_form.html.erb
<%= form_for(sediment) do |f| %>
  <% if sediment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sediment.errors.count, "error") %> prohibited this sediment from being saved:</h2>

      <ul>
      <% sediment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :composition %>
    <%= f.text_field :composition %>
  </div>

  <div class="field">
    <%= f.label :res_type %>
    <%= f.text_field :res_type %>
  </div>

  <div class="field">
    <%= f.label :weight %>
    <%= f.text_field :weight %>
  </div>

  <div class="field">
    <%= f.label :volume %>
    <%= f.text_field :volume %>
  </div>

  <div class="field">
    <%= f.label :data_registered %>
    <%= f.date_select :data_registered %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sediments/edit.html.erb
<h1>Editing Sediment</h1>

<%= render 'form', sediment: @sediment %>

<%= link_to 'Show', @sediment %> |
<%= link_to 'Back', sediments_path %>

app/views/sediments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sediments</h1>

<table>
  <thead>
    <tr>
      <th>Composition</th>
      <th>Weight</th>
      <th>Type</th>
      <th>Local</th>
      <th>Data created</th>
      <th>Data registered</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sediments.each do |sediment| %>
      <tr>
        <td><%= sediment.composition %></td>
        <td><%= sediment.weight %></td>
        <td><%= sediment.res_type %></td>
        <td><%= sediment.local %></td>
        <td><%= sediment.data_created %></td>
        <td><%= sediment.data_registered %></td>
        <td><%= link_to 'Show', sediment %></td>
        <td><%= link_to 'Edit', edit_sediment_path(sediment) %></td>
        <td><%= link_to 'Destroy', sediment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sediment', new_sediment_path %>

app/views/sediments/new.html.erb
<h1>New Sediment</h1>

<%= render 'form', sediment: @sediment %>

<%= link_to 'Back', sediments_path %>

app/views/sediments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Composition:</strong>
  <%= @sediment.composition %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @sediment.weight %>
</p>

<p>
  <strong>Local:</strong>
  <%= @sediment.local %>
</p>

<p>
  <strong>Data created:</strong>
  <%= @sediment.data_created %>
</p>

<p>
  <strong>Data registered:</strong>
  <%= @sediment.data_registered %>
</p>

<%= link_to 'Edit', edit_sediment_path(@sediment) %> |
<%= link_to 'Back', sediments_path %>